version: "3.8"
services:
  pocketbase:
    image: docker.io/bakirg/pocketbase-docker:0.28.0
    restart: unless-stopped
    ports:
      - "8090"
    volumes:
      - "/etc/dokploy/templates/${HASH}/data:/app/pb_data"
      - "/etc/dokploy/templates/${HASH}/migrations:/app/pb_migrations" 
      - "/etc/dokploy/templates/${HASH}/hooks:/app/pb_hooks" 
      - "/etc/dokploy/templates/${HASH}/public:/app/pb_public" 
    healthcheck:
      test: wget -q --spider http://localhost:8090/api/health || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
