[variables]
main_domain = "${domain}"

[config]
mounts = [ ]

  [[config.domains]]
  serviceName = "penpot-frontend"
  port = 80
  host = "${main_domain}"

  [config.env]
  DOMAIN_NAME = "${main_domain}"
