# the webserver can take a while to start up, so don't be alarmed if it takes a few minutes to get a response
services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
    volumes:
      - vaultwarden:/data
    expose:
      - 80

volumes:
  vaultwarden:
