version: '3.8'

services:
  bytestash:
    image: ghcr.io/jordan-dalby/bytestash:1.5.6
    restart: unless-stopped
    ports:
      - "5000"
    environment:
      - BASE_PATH=
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXPIRY=24h
      - ALLOW_NEW_ACCOUNTS=true
      - DEBUG=true
      - DISABLE_ACCOUNTS=false
      - DISABLE_INTERNAL_ACCOUNTS=false
      - OIDC_ENABLED=false
      - OIDC_DISPLAY_NAME=
      - OIDC_ISSUER_URL=
      - OIDC_CLIENT_ID=
      - OIDC_CLIENT_SECRET=
      - OIDC_SCOPES=
    volumes:
      - snippets:/data/snippets

volumes:
  snippets: 